layout_spectrum: 0.06368671
color:
  saturation: 0.7401434
  brandStrength: 0.4338087
  lightness: 0.7383512
  rhythmicContrast: 0.4478867
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.2622126
name: Lee Stobby Entertainment
